#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."

STAMP=$(date +%F-%H%M%S)
tar -czf "../coinbase_pipeline-backup-$STAMP.tgz" .

# keep your existing ignore rules, but ensure basics
awk 'BEGIN{print "# autogenerated harden"} /./{print}' .gitignore 2>/dev/null || true
git add -A
git commit -m "chore: update working tree before fixed-page Notion patch" || echo "ℹ️ nothing to commit"

# ensure origin
git remote get-url origin >/dev/null 2>&1 || git remote add origin git@github.com:andybahtwin-maker/coinbase_pipeline.git

# push (with lease)
git push --force-with-lease origin main
